---
- name: SR Health Check - Wait for API to return 200
  uri:
    url: "{{schema_registry_http_protocol}}://{{inventory_hostname}}:{{schema_registry_listener_port}}/subjects"
    status_code: 200
    validate_certs: false
    # Basic auth header is redundant for non rbac install
    #url_username: "{{schema_registry_health_check_user}}"
    #url_password: "{{schema_registry_health_check_password}}"
    #force_basic_auth: true
  register: result1
  until: result1.status == 200
  retries: 10
  delay: 5
  when: not schema_registry_ssl_mutual_auth_enabled|bool
  ignore_errors: true

