---
### Boolean to have cp-ansible install Java on hosts
install_java: true

### Java Package to install on RHEL/Centos hosts. Possible values java-1.8.0-openjdk or java-11-openjdk
redhat_java_package_name: java-1.8.0-openjdk

### Base URL for Confluent's RPM and Debian Package Repositories
confluent_common_repository_baseurl: "https://packages.confluent.io"

### Yum Repo Details
confluent_common_repository_redhat_baseurl: "{{confluent_common_repository_baseurl}}/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1
confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/7"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 1

### Confluent Kafka Packages on each Node
kafka_packages:
    - confluent-ce-kafka-http-server
    - confluent-common
    - confluent-control-center
    - confluent-control-center-fe
    - confluent-hub-client
    - confluent-kafka-connect-replicator
    - confluent-kafka-rest
    - confluent-metadata-service
    - confluent-rebalancer
    - confluent-rest-utils
    - confluent-schema-registry
    - confluent-security
    - confluent-server-rest
    - confluent-telemetry
    - confluent-ksqldb
    - confluent-kafka-mqtt
    - confluent-server
    - confluent-cli
