---
#- name: Ensure Plugin Dirs
#  file:
#    path: "{{item}}"
#    state: directory
#    group: "{{kafka_connect_group}}"
#    owner: "{{kafka_connect_user}}"
#    mode: 0755
#  when: item != '/usr/share/java'
#  with_items: "{{ kafka_connect_final_properties['plugin.path'].split(',') }}"

- name: Installing Remote Plugins
  unarchive:
    src: "{{item}}"
    dest: "{{kafka_connect_plugins_dest}}"
    group: "{{kafka_connect_group}}"
    owner: "{{kafka_connect_user}}"
    mode: 0755
    remote_src: true
  with_items: "{{kafka_connect_plugins_remote}}"
  when: kafka_connect_plugins_remote|length > 0
  notify: restart connect-service

