---
# Cannot use Block/Rescue in Ansible Handlers: https://github.com/ansible/ansible/issues/14270
# Implementing try/catch logic with ignore_errors and conditionals
- name: Kafka Connect Health check - Wait for API to return 200
  uri:
    url: "{{kafka_connect_http_protocol}}://{{inventory_hostname}}:{{kafka_connect_rest_port}}/connectors"
    status_code: 200
    validate_certs: false
    # Basic auth header is redundant for non rbac install
    #url_username: "{{kafka_connect_health_check_user}}"
    #url_password: "{{kafka_connect_health_check_password}}"
    #force_basic_auth: true
  register: result1
  until: result1.status == 200
  retries: 10
  delay: 10
  when: not kafka_connect_ssl_mutual_auth_enabled|bool
  ignore_errors: true
