---
# To use variables of this file in roles say zookeeper/tasks/main.tf or others/tasks/main.tf
# make sure you have  zookeeper/meta/main.tf or others/meta/main.tf with dependencies defined
#dependencies:
#  - role: confluent.variables

#### Zookeeper Variables ####
confluent_repo_version: "{{ confluent_package_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}"
zookeeper_user: cp-kafka
zookeeper_group: confluent

zookeeper:
  version: 3.7.0
  zk_application_path: /etc/kafka
  log4j_file: /etc/kafka/zookeeper-log4j.properties
  configuration:
    port: 2181
    log_path: /var/log/zookeeper
    data_dir: /var/lib/zookeeper
    tick_time: 2000
    init_limit: 5
    sync_limit: 2


#### Kafka Broker Variables ###
kafka_broker_user: cp-kafka
kafka_broker_group: confluent

kafka_broker:
  confluent_version: 7.2
  kafka_application_path: /etc/kafka
  config_file: "/etc/kafka/server.properties"
  log4j_file: /etc/kafka/log4j.properties
  configuration:
    port: 9092
    data_dir: /var/lib/kafka
    logs_dir: /var/lib/kafka/data
    logs_path: /var/log/kafka
    network_threads: 3
    num_partitions: 1
    log_retention_hours: 24
    log_retention_bytes: 1073741824
    log_segment_bytes: 1073741824
    log_retention_check_interval: 300000
    log_cleaner_enable: false
    zk_connection_timeout: 60000


################ Kafka Connect Properties #############
# Health check
kafka_connect_ssl_mutual_auth_enabled: "false"
kafka_connect_http_protocol: "{{ 'https' if kafka_connect_ssl_mutual_auth_enabled|bool else 'http' }}"
kafka_connect_rest_port: "{{ '18083' if kafka_connect_ssl_mutual_auth_enabled|bool else '8083' }}"

kafka_connect_plugins_dest: /usr/share/java
kafka_connect_user: cp-kafka-connect
kafka_connect_group: confluent


################ Schema Registry Properties #############
## Health check
schema_registry_ssl_mutual_auth_enabled: "false"
schema_registry_http_protocol: "{{ 'https' if schema_registry_ssl_mutual_auth_enabled|bool else 'http' }}"
schema_registry_listener_port: "{{ '18081' if schema_registry_ssl_mutual_auth_enabled|bool else '8081' }}"

# User, Group, Log Dir etc are default ones


################ KSQL Properties #############
# Health check
ksql_ssl_mutual_auth_enabled: "false"
ksql_http_protocol: "{{ 'https' if ksql_ssl_mutual_auth_enabled|bool else 'http' }}"
ksql_listener_port: "{{ '18088' if ksql_ssl_mutual_auth_enabled|bool else '8088' }}"

# User, Group, Log Dir etc are default ones


################ Kafka Rest Properties #############
# Health check
kafka_rest_ssl_mutual_auth_enabled: "false"
kafka_rest_http_protocol: "{{ 'https' if kafka_rest_ssl_mutual_auth_enabled|bool else 'http' }}"
kafka_rest_port: "{{ '18082' if kafka_rest_ssl_mutual_auth_enabled|bool else '8082' }}"

# User, Group, Log Dir etc are default ones

################ Control Center Properties #############
# Health check
rbac_enabled: "false"
control_center_http_protocol: "{{ 'https' if rbac_enabled|bool else 'http' }}"
control_center_port: "{{ '19021' if rbac_enabled|bool else '9021' }}"

# User, Group, Log Dir etc are default ones

